spring.application.name=student-agent

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Gemini API Config
gemini.api.url=https://{BaseUrl}/v1/projects/{Project}/locations/{Location}/publishers/google/models/gemini-2.5-flash:generateContent
# REPLACE THIS WITH YOUR ACTUAL TOKEN
gemini.api.token=<API_TOKEN>